
hld_content_generation_task:
  output_file: output/hld_crew_output.txt
  description: >
    # Objectives

    As the Learning Experience Designer, your primary task is to generate a slide-based HLD for a course.

    Your process should involve the following steps, informed by the following inputs:
    
    <inputs>
    The product title: {product_title}

    The client name is: {client_name}

    The course delivery method: {course_delivery_method}

    The course delivery modality: {course_delivery_modality}

    The course duration in hours: {course_duration_h}

    The course description: {course_description}

    The course's business outcomes: {course_business_outcomes}

    The client's priorities: {client_priorities}

    The primary learner persona job role: {primary_persona_job_role}

    The learner persona description: {learner_persona_description}

    The learner persona attributes and background: {learner_persona_attributes_and_background}

    The learner persona's existing foundational knowledge related to the course topic: {learner_persona_existing_knowledge}

    The high-level learning outcomes of the course: {course_learning_outcomes}

    The software and tools that will be used in the course: {course_software_and_tools}
    </inputs>

    If no client name is provided, assume there's no client.

    Ensure the client's priorities are included and emphasized in the output.

    You must:
   
    ## Analyze Inputs and Infer Context
        
    Review the provided inputs. From these you will develop the following outputs:
    
    - Define product learning path

    Use the following information on each to help you with this task:

    - Each learning path component has a heading followed by multi-sentence description
    - A learning path consists of 3-4 components, but if there is a strong case for either 2 or 5 components, that can work, but please include your rationale for going outside of the norm.
    - Reference the following table for contextual reference:
    
    |  Heading                            |    Description                                                                                                                                          | 
    |:-----------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|
    |  Design Thinking | Understand various UX design frameworks. Explore topics such as convergent and divergent thinking. Define the various roles that make up UX. |
    |  UX Research Skills | Discover foundational research methodologies and how those are used to iterate and make meaningful improvements to improve the user experience. |
    |  UX Design Skills | Get hands-on practice in UX design skills, including ideation, sketching, wireframing, prototyping, visual design, and maps and user flows. |
    |  Design Systems | Learn about foundational design system theory and how it is used by a team to create cohesive and on-brand designs. |

  expected_output: >
    A comprehensive HLD structured according to 
    the following:

    Slide 1: Title Card

    [tktk Product Title] for [tktk Client Name]
    Slide 2: Program Title, Talking Points, and Details

    [tktk Product Title]

    [tktk delivery method]
    [tktk delivery modality]
    [tktk delivery hours] Hours

    [tktk Product hook]

    [tktk Product description]

    Business outcomes:
    [tktk Product outcome 1]
    [tktk Product outcome 2]
    [tktk Product outcome 3]

    [tktk delivery hours] hours of training

    [tktk Product Learning Path Headline 1]
    [tktk Product learning path 1]
    [tktk Product Learning Path Headline 2]
    [tktk Product learning path 2]
    [tktk Product Learning Path Headline 3]
    [tktk Product learning path 3]
    Slide 3: Stakeholder Insights 
    [tktk Client Name]

    What we heard in stakeholder interviews:
    [tktk Client-specific detail 1]
    [tktk Client-specific detail 2]
    [tktk Client-specific detail 3]
    [tktk Client-specific detail 4]
    [tktk Client-specific detail 5]
    Slide 4: Learner Persona
    [tktk Product Title] is specifically designed for [tktk Primary Persona Job Role].
    [tktk Learner persona description]
    Attributes and Background:
    [tktk Attribute and background 1]
    [tktk Attribute and background 2]
    [tktk Attribute and background 3]

    Foundational Skills: 
    [tktk prereq related to course 1]
    [tktk prereq related to course 2]
    [tktk prereq related to course 3]
    Slide 5: Learning Goals
    What a [tktk Primary Persona Job Role] will be able to do by the end of the course:
    [tktk Product learning goal 1]
    [tktk Product learning goal 2]
    [tktk Product learning goal 3]
    [tktk Product learning goal 4]
    [tktk Product learning goal 5]
    Slide 6: Sample of Content
    The LED will fill in these details.
    Slide 7: Software and Tools
    [tktk Software or Tool 1]
    [tktk Software or Tool 2]
    [tktk Software or Tool 3]
    [tktk Software or Tool 4]
    [tktk Software or Tool 5]
    [tktk Software or Tool 6]
    [tktk Software or Tool 7]
    [tktk Software or Tool 8]
    [tktk Software or Tool 9]
    [tktk Software or Tool 10]
    [tktk Software or Tool 11]
    [tktk Software or Tool 12]
    [tktk Software or Tool 13]
    [tktk Software or Tool 14]
    [tktk Software or Tool 15]
    [tktk Software or Tool 16]
    [tktk Software or Tool 17]
    [tktk Software or Tool 18]
    [tktk Software or Tool 19]
    [tktk Software or Tool 20]

  agent: led_agent

